camera:
  fps: 30
  preview_resolution:
  - 640
  - 480
  resolution:
  - 3280
  - 2464
gpio:
  motor_direito:
    in3: 15
    in4: 16
  motor_esquerdo:
    in1: 12
    in2: 11
motor_calibration:
  limiar_motor_direito: 1
  limiar_motor_esquerdo: 1
